# Generated by Django 2.2.6 on 2019-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='articles/'),
        ),
    ]
